// Writes _headers with a CSP that allows the inline blocks by SHA-256 hash.
// Run with --check to exit 1 when _headers no longer matches index.html.

import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const HTML = path.join(ROOT, 'index.html');
const HEADERS = path.join(ROOT, '_headers');

// Returns the CSP hash of every inline block of that tag.
function hashesOf(html, tag) {
  const re = new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)</${tag}>`, 'g');
  const out = [];
  for (const match of html.matchAll(re)) {
    // External scripts are covered by 'self' and hash to the empty string.
    if (/\ssrc=/.test(match[0])) continue;
    // JSON-LD is data, not executable code.
    if (/type="application\/ld\+json"/.test(match[0])) continue;
    const digest = createHash('sha256').update(match[1], 'utf8').digest('base64');
    out.push(`'sha256-${digest}'`);
  }
  return out;
}

export function buildHeaders(html) {
  const scripts = hashesOf(html, 'script').join(' ');
  const styles = hashesOf(html, 'style').join(' ');

  const csp = [
    `default-src 'self'`,
    `base-uri 'none'`,
    `object-src 'none'`,
    `frame-ancestors 'none'`,
    `form-action 'self'`,
    `connect-src 'self'`,
    `script-src 'self' ${scripts}`,
    `style-src 'self' ${styles}`,
    `font-src 'self'`,
    `img-src 'self' data:`,
    `manifest-src 'self'`,
    `worker-src 'none'`,
    `upgrade-insecure-requests`,
  ].join('; ');

  return `# Generated by script/csp.js. Do not edit by hand.
# Regenerate after changing any inline <script> or <style> in index.html.

/*
  Content-Security-Policy: ${csp}
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: accelerometer=(), autoplay=(), camera=(), display-capture=(), encrypted-media=(), fullscreen=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), usb=(), xr-spatial-tracking=(), interest-cohort=()
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin

/assets/*
  Cache-Control: public, max-age=3600

/src/*
  Cache-Control: public, max-age=3600
`;
}

const expected = buildHeaders(fs.readFileSync(HTML, 'utf8'));

if (process.argv.includes('--check')) {
  const actual = fs.existsSync(HEADERS) ? fs.readFileSync(HEADERS, 'utf8') : '';
  if (actual !== expected) {
    console.error(
      '\x1b[31m[FAIL]\x1b[0m _headers is stale: an inline <script> or <style> in index.html changed.\n' +
        '       The deployed page would be blocked by its own CSP.\n' +
        '       Run: node script/csp.js',
    );
    process.exit(1);
  }
  console.log('\x1b[32m[PASS]\x1b[0m CSP hashes match the inline blocks in index.html');
} else {
  fs.writeFileSync(HEADERS, expected);
  console.log(`Wrote ${path.relative(ROOT, HEADERS)}`);
}
