// Generates _headers, and verifies it still matches index.html.
//
// The page keeps two inline blocks on purpose: a script that applies the
// stored theme before first paint (moving it to a file would reintroduce the
// flash it exists to prevent) and a style block for the mobile navigation.
// Both are allowed by SHA-256 hash rather than 'unsafe-inline', so the policy
// still blocks anything injected later.
//
//   node script/csp.js          write _headers
//   node script/csp.js --check  exit 1 if _headers is stale
//
// Run --check in the test suite: editing an inline block without regenerating
// silently breaks the live page while every local check stays green.

import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const HTML = path.join(ROOT, 'index.html');
const HEADERS = path.join(ROOT, '_headers');

function hashesOf(html, tag) {
  const re = new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)</${tag}>`, 'g');
  const out = [];
  for (const match of html.matchAll(re)) {
    // External scripts are covered by 'self' and hash to the empty string.
    if (/\ssrc=/.test(match[0])) continue;
    // JSON-LD is data, not executable code.
    if (/type="application\/ld\+json"/.test(match[0])) continue;
    const digest = createHash('sha256').update(match[1], 'utf8').digest('base64');
    out.push(`'sha256-${digest}'`);
  }
  return out;
}

export function buildHeaders(html) {
  const scripts = hashesOf(html, 'script').join(' ');
  const styles = hashesOf(html, 'style').join(' ');

  const csp = [
    `default-src 'self'`,
    `base-uri 'none'`,
    `object-src 'none'`,
    `frame-ancestors 'none'`,
    `form-action 'self' https://formspree.io`,
    `connect-src 'self' https://formspree.io`,
    `script-src 'self' ${scripts}`,
    `style-src 'self' ${styles} https://fonts.googleapis.com`,
    `font-src 'self' https://fonts.gstatic.com`,
    `img-src 'self' data:`,
    `upgrade-insecure-requests`,
  ].join('; ');

  return `# Generated by script/csp.js. Do not edit by hand.
# Regenerate after changing any inline <script> or <style> in index.html.

/*
  Content-Security-Policy: ${csp}
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), interest-cohort=()
  Cross-Origin-Opener-Policy: same-origin

/assets/*
  Cache-Control: public, max-age=31536000, immutable

/src/*
  Cache-Control: public, max-age=3600
`;
}

const expected = buildHeaders(fs.readFileSync(HTML, 'utf8'));

if (process.argv.includes('--check')) {
  const actual = fs.existsSync(HEADERS) ? fs.readFileSync(HEADERS, 'utf8') : '';
  if (actual !== expected) {
    console.error(
      '\x1b[31m[FAIL]\x1b[0m _headers is stale: an inline <script> or <style> in index.html changed.\n' +
        '       The deployed page would be blocked by its own CSP.\n' +
        '       Run: node script/csp.js',
    );
    process.exit(1);
  }
  console.log('\x1b[32m[PASS]\x1b[0m CSP hashes match the inline blocks in index.html');
} else {
  fs.writeFileSync(HEADERS, expected);
  console.log(`Wrote ${path.relative(ROOT, HEADERS)}`);
}
